input =
      pipeline '\n'
    | pipeline EOF
    | '\n'
    | EOF
;

pipeline = 
    command_line { '|' command_line }

command_line =
    command [ redirect_list ]
;

command =
    WORD { WORD }        
;

redirect_list =
    redirect { redirect }
;

redirect =
      '>'  WORD
    | '1>' WORD
    | '2>' WORD
    | '>>' WORD
    | '1>>' WORD
    | '2>>' WORD
;
